### PR TITLE
Proposition for an app changelog

### PR DESCRIPTION
**Pull request by maniackcrudelis**
## Problem
- *From https://pad.lqdn.fr/p/yunohost-21-05-2019, we've decided to add a changelog for each app.*

## Solution
- *Try to define a template for a changelog*

## PR Status
- [ ] Code finished.
- [ ] Tested with Package_check.
- [ ] Fix or enhancement tested.
- [ ] Upgrade from last version tested.
- [ ] Can be reviewed and tested.

## Validation
---
- [x] **Code review** Kay0u
- [x] **Approval (LGTM)** Kay0u
*Code review and approval have to be from a member of @YunoHost/apps group*
When the PR is marked as ready to merge, you have to wait for 3 days before really merging it.

### CODE REVIEW

**Comment by maniackcrudelis** [comment]
@YunoHost-Apps/apps-group

**Comment by kay0u** [comment]
Can be merged in 3 days

**Comment by JimboJoe** [comment]
What about using a [standard proposal](https://keepachangelog.com/en/1.0.0/)...? :thinking:

**Comment by maniackcrudelis** [comment]
How do we know that's a standard ?

I don't think I've ever seen that exact syntax for a changelog. I'm not sure either I've ever seen a common syntax for a changelog...
As long as it's easy to write and easy to parse, we can discuss the syntax.

**Comment by JimboJoe** [comment]
Oh, it's certainly not a standard (yet...?), but as I stumbled upon it the other day, I thought it was an interesting initiative (quite comparable to [semantic versioning](https://semver.org/) for versioning).

**Comment by maniackcrudelis** [comment]
Well make a proposition with this syntax from the current changelog I made, so we could see what's the differences and decide if it could be more interesting.
I don't especially want to keep my proposition. That's just a proposition, if we could find better, let's improve it.

**Comment by maniackcrudelis** [comment]
@JimboJoe should we wait for another version from what you've found or merge as it is ?

**Comment by JimboJoe** [comment]
[Here](https://pad.lqdn.fr/p/yunohost_apps_changelog) is a proposal based on a discussed changelog format.
Not that much different but a bit better...?

**Comment by maniackcrudelis** [comment]
Ok, made a proposition in a second file, from your pad.

Kept the title without the hash signs, to not interfere with the log entries for the parser. It's easier.
Removed the comment, as it's not really the same syntax. And a changelog is obviously about what new in an app.
Added a hash sign for the sub titles, to make them smaller.
A kept 2 lines between each entries in the log for people who would read it without a markdown interpreter.

The parser will certainly have to be modified, but nothing big.

**Comment by JimboJoe** [comment]
For the syntax, the web page is not up-to-date with the [reference changelog](https://github.com/olivierlacan/keep-a-changelog/blob/master/CHANGELOG.md).

You made adaptations made on what it looked like when rendered... by which engine? If it's github, that doesn't feel like you ;-)
I would be more in favor of a strictly hierarchical syntax, hence one hash for the title, two for the version, three for the change category...

**Comment by maniackcrudelis** [comment]
I made adaptation based on these 3 points

- The parser, https://github.com/YunoHost-Apps/leed_ynh/pull/24, for the main title, not using a hash sign at the beginning prevent any miss reading. For the same result in markdown (I believe)
- Github markdown engine indeed, for the additional hash sign for the subtitle. Because mostly, when read as a markdown file, it's going to be here.
- The raw file, for the additional lines when read from a command line or text editor.

**Comment by maniackcrudelis** [comment]
I hate that fucking git...
When proposing to merge in CLI, you can't see what and why...

So opening a fucking another PR to have ONLY the changelog...

**Pull request closed without merging**
